slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    odom_frame: odom
    base_frame: body_link
    scan_topic: /scan
    resolution: 0.05
    max_laser_range: 12.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1

