<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">



  <!-- Define robot parameters -->
  <xacro:property name="body_link_x_dim" value="1"/>
  <xacro:property name="body_link_y_dim" value="0.6"/>
  <xacro:property name="body_link_z_dim" value="0.3"/>

  <!-- Wheel dimensions -->
  <xacro:property name="wheel_link_radius" value="0.15"/>
  <xacro:property name="wheel_link_length" value="0.1"/>
  <xacro:property name="wheel_link_z_location" value="-0.1"/>

  <!-- Material Density -->
  <xacro:property name="body_density" value="2710.0"/>
  <xacro:property name="wheel_density" value="2710.0"/>

  <!-- Pi constant -->
  <xacro:property name="pi" value="3.14159"/>

  <!-- Robot body and wheel mass -->
  <xacro:property name="body_mass" value="${body_density * body_link_x_dim * body_link_y_dim * body_link_z_dim}"/>
  <xacro:property name="wheel_mass" value="${wheel_density * pi * wheel_link_radius * wheel_link_radius * wheel_link_length}"/>


  <!-- Moments of inertia of the wheels -->
    <xacro:property name="Iz_wheel" value="${0.5 * wheel_mass * wheel_link_radius * wheel_link_radius}"/>
    <xacro:property name="I_wheel" value="${(1.0/12.0) * wheel_mass * (3 * wheel_link_radius * wheel_link_radius + wheel_link_length * wheel_link_length)}"/>


    <!-- Complete inertal section of the wheels -->
    <xacro:macro name="inertia_wheel">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${I_wheel}" ixy="0" ixz="0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}"/>
        </inertial>
    </xacro:macro>

    <xacro:include filename="$(find mobile_robot)/model/robot.gazebo"/>

    <!-- FROM HERE WE DEFINE LINKS AND JOINTS -->

    <!-- Dummy Link -->
    <link name="dummy">
    </link>
    <joint name="dummy_joint" type="fixed">
      <parent link="dummy"/>
      <child link="body_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Body Link -->
    <link name="body_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${body_mass}"/>
            <inertia ixx="${(1.0/12.0) * body_mass * (body_link_y_dim * body_link_y_dim + body_link_z_dim * body_link_z_dim)}"
                     ixy="0" ixz="0"
                     iyy="${(1.0/12.0) * body_mass * (body_link_x_dim * body_link_x_dim + body_link_z_dim * body_link_z_dim)}"
                     iyz="0"
                     izz="${(1.0/12.0) * body_mass * (body_link_x_dim * body_link_x_dim + body_link_y_dim * body_link_y_dim)}"/>
        </inertial>
    </link>

    <!-- Back right Wheel Link and joint -->
    <joint name="wheel1_joint" type="continuous">
      <parent link="body_link"/>
       <child link="wheel1_link"/>
       <origin xyz="${-body_link_x_dim/2+1*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
       <axis xyz="0 1 0"/>
       <limit effort="1000" velocity="1000"/>
       <dynamics damping="1" friction="1"/>
    </joint>

    <link name="wheel1_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </collision>
      <xacro:inertia_wheel/>
    </link>

    <!-- Back left Wheel Link and joint -->
    <joint name="wheel2_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel2_link"/>
        <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1" friction="1"/>
    </joint>

    <link name="wheel2_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </collision>
      <xacro:inertia_wheel/>

    </link>

    <!-- Front right Wheel Link and joint -->
    <joint name="wheel3_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel3_link"/>
        <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1" friction="1"/>
    </joint>

    <link name="wheel3_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </collision>
      <xacro:inertia_wheel/>
    </link>

    <!-- Front left Wheel Link and joint -->
    <joint name="wheel4_joint" type="continuous">
        <parent link="body_link"/>
        <child link="wheel4_link"/>
        <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1" friction="1"/>
    </joint>
    <link name="wheel4_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
        <geometry>
          <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
        </geometry>
      </collision>
      <xacro:inertia_wheel/>
    </link>

    <!-- Lidar Link and joint -->
    <link name="lidar_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="0.03" length="0.06"/></geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="0.03" length="0.06"/></geometry>
      </collision>
    </link>

    <joint name="lidar_joint" type="fixed">
      <parent link="body_link"/>
      <!-- put lidar 0.2 m above the body; tweak as you like -->
      <child link="lidar_link"/>
      <origin xyz="0 0 ${body_link_z_dim/2 + 0.03}" rpy="0 0 0"/>
    </joint>

    <link name="imu_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
      </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
      <parent link="body_link"/>
      <child link="imu_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot>







